In [1]:
import numpy as np 

### Create an numpy array

In [2]:

a = np.array([1,2,3,4,5])#list
b = np.array((1,2,3,4,5))#tuple
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]


###  Create 2d array

In [3]:
arr = np.array([(1,2,3),(2,3,4)])
print(arr)

[[1 2 3]
 [2 3 4]]


### Check dimension

In [4]:

arr.ndim

2

### Item size : byte size of each element

In [5]:
arr.itemsize

4

#### Datatype

In [6]:
arr.dtype

dtype('int32')

### Create 3D array

In [7]:
#arr3 = np.array([((1,2,4),(3,5,6)),((1,2,4),(3,5,6))])
arr3 = np.array([[[1,2,4],[3,5,6]],[[1,2,4],[3,5,6]]])
print(arr3)
print("Dimension:",arr3.ndim)
print("Shape : ",arr3.shape)

[[[1 2 4]
  [3 5 6]]

 [[1 2 4]
  [3 5 6]]]
Dimension: 3
Shape :  (2, 2, 3)


### Accessing array elements

In [8]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
arr[0][1]

2

In [10]:
#Get a specific row
arr[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
#Get a specific column
arr[:,0]

array([1, 8])

In [12]:
# Getting a little more [startindex: endindex: stepsize]
arr[0, 1:6:2]

array([2, 4, 6])

In [13]:
print(arr[0, 1:-2:2]) #Negative index start from backside lastindex is -1, second last is -2 and so on
print(arr[0, 1:-1:2]) 

[2 4]
[2 4 6]


In [14]:
arr3

array([[[1, 2, 4],
        [3, 5, 6]],

       [[1, 2, 4],
        [3, 5, 6]]])

In [15]:
print(arr3[1][0][1])
print(arr3[1,0,1])#another method

2
2


In [16]:
#Changing array element
arr3[1][0][1] = 2

In [17]:
arr3

array([[[1, 2, 4],
        [3, 5, 6]],

       [[1, 2, 4],
        [3, 5, 6]]])

### Initialize different types of array

In [18]:
a = np.zeros((2,3),dtype='int32')

In [19]:
a

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones((3,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
#Create an array with some different element
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [22]:
#create an identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
#create an array in a range
a = np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [24]:
#reshape
a.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [25]:
# Random decimal number
np.random.rand(4,2)

array([[0.91915044, 0.8278741 ],
       [0.71774102, 0.62579209],
       [0.37283022, 0.52260343],
       [0.81224233, 0.02619715]])

In [26]:
# Random Integer values
np.random.randint(7,size=(3,3))
#np.random.randint(4,7,size=(3,3))

array([[4, 3, 0],
       [3, 6, 5],
       [0, 1, 4]])

In [27]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Be careful while copying array


In [28]:
#Normal variable copying
a = 6
b= a
print(b,"  ",a)
b=4
print(b, " ",a)

6    6
4   6


In [29]:
#Numpy array
a = np.array([1,2,3])
b= a #now b and a are pointing same memory location 
b[0]=100
print(b)
print(a)


[100   2   3]
[100   2   3]


# axis in 3D

In [30]:
import numpy as np

In [31]:
arr = np.arange(1,25).reshape(2,3,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### axis=0

In [32]:
arr[0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [34]:
arr[0]+arr[1]

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [35]:
np.sum(arr,axis=0)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

### axis = 1

In [36]:
arr[0][0]

array([1, 2, 3, 4])

In [37]:
arr[0][1]

array([5, 6, 7, 8])

In [38]:
print(arr[0][0])
print(arr[0][1])
print(arr[0][2])
print(arr[1][0])
print(arr[1][1])
print(arr[1][2])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[17 18 19 20]
[21 22 23 24]


In [39]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [40]:
arr[0][0] + arr[0][1] + arr[0][2]

array([15, 18, 21, 24])

In [41]:
arr[1][0] + arr[1][1] + arr[1][2]

array([51, 54, 57, 60])

In [42]:
np.sum(arr,axis=1)

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

### axis=2

In [43]:
arr[0][0][0]

1

In [44]:
print(   arr[0][0][0] + arr[0][0][1] + arr[0][0][2] + arr[0][0][3]  )
print(   arr[0][1][0] + arr[0][1][1] + arr[0][1][2] + arr[0][1][3]  )
print(   arr[0][2][0] + arr[0][2][1] + arr[0][2][2] + arr[0][2][3]  )

10
26
42


In [45]:
print(   arr[1][0][0] + arr[1][0][1] + arr[1][0][2] + arr[1][0][3]  )
print(   arr[1][1][0] + arr[1][1][1] + arr[1][1][2] + arr[1][1][3]  )
print(   arr[1][2][0] + arr[1][2][1] + arr[1][2][2] + arr[1][2][3]  )

58
74
90


In [46]:
np.sum(arr,axis=2)

array([[10, 26, 42],
       [58, 74, 90]])

# numpy.swapaxes

In [47]:
import numpy as np

In [48]:
x = np.arange(1,25).reshape(2,3,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [49]:
a = np.swapaxes(x,0,2)
print(a.shape)
print(a)
#2,3,4

(4, 3, 2)
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


In [50]:
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [51]:
b = np.swapaxes(x,0,1)
print(b.shape)
print(b)
# 2 3 4

(3, 2, 4)
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]


# Mathematical Operations

In [52]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [53]:
np.add(a,b)

array([ 2,  4,  6,  8, 10])

In [54]:
np.subtract(a,b)

array([0, 0, 0, 0, 0])

In [55]:
np.multiply(a,b)

array([ 1,  4,  9, 16, 25])

In [56]:
np.divide(a,b)

array([1., 1., 1., 1., 1.])

In [57]:
np.power(a,b)

array([   1,    4,   27,  256, 3125], dtype=int32)

In [58]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [59]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [60]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [61]:
#log
np.log(a) #Natural log

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [62]:
np.log2(a) #log base 2

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [63]:
np.log10(a) #log base 10

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [64]:
#Mean
np.mean(a)

3.0

In [65]:
#standard deviation
np.std(a)

1.4142135623730951

In [66]:
#Variance
np.var(a)

2.0

In [67]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

# Numpy functions

In [68]:
a = np.array([1,2,5,3,9])
a

array([1, 2, 5, 3, 9])

In [69]:
np.min(a)

1

In [70]:
np.max(a)

9

In [71]:
np.sum(a)

20

In [72]:
#Lets do same for 2d or 3d

In [73]:
a = np.array([[17,33,3],[1,2,3]])
a

array([[17, 33,  3],
       [ 1,  2,  3]])

In [74]:
np.min(a)

1

In [75]:
#Row wise minimum
np.min(a,axis=1)

array([3, 1])

In [76]:
#Column wise min
np.min(a,axis =0)

array([1, 2, 3])

In [77]:
#Same for sum
np.sum(a)

59

In [78]:
np.sum(a,axis=1)#row wise

array([53,  6])

In [79]:
np.sum(a,axis =0) #column wise

array([18, 35,  6])

In [80]:
#Vertical stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
#Horizontal stacking
h1 = np.array([1,2,3,4])
h2 =np.array([5,6,7,8])
np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# EigenValues
# Matrix Norms
# Inverse
# etc...

## Indexing & Slicing
"Indexing" is used to obtain individual elements from an array, but it can also be used to obtain entire rows, columns or planes from multi-dimensional arrays.

“Slicing” means getting a subset of elements from an iterable based on their indices.

#### Indexing in 1 dimension

In [83]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [84]:
a[1]

2

In [85]:
a[3]

4

#### Indexing in 2 dimensions

In [86]:
a = np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15)])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [87]:
a[2,2]

13

In [88]:
#Picking a row
a[1]

array([ 6,  7,  8,  9, 10])

#### Indexing in 3 dimensions

In [89]:
a = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

In [90]:
a

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [91]:
a[1, 0, 0]

20

In [92]:
#Picking a row
a[1,0]

array([20, 21, 22])

In [93]:
#Picking a matrix
a[2]

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

# Slicing

In [94]:
#Slicing 1D numpy arrays
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [95]:
a[1:4]

array([2, 3, 4])

In [96]:
#Slicing 2D numpy arrays

In [97]:
a2 = np.array([(1,2,3,4),(5,6,7,8)])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [98]:
a2[:,2:]

array([[3, 4],
       [7, 8]])

In [99]:
a2[:,:2]

array([[1, 2],
       [5, 6]])

In [100]:
a2 = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29]])
a2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [101]:
a2[1:,:2]

array([[15, 16],
       [20, 21],
       [25, 26]])

In [102]:
a2[:-3,3:]

array([[13, 14]])

In [103]:
# exercise: slice 16 17 21 22 

# Numpy array vs list
### 1.Comparing Memory use

In [104]:
import numpy as np
import time
import sys

In [105]:
a = np.arange(100)

In [106]:
print("Size of numpy array is: ",a.size * a.itemsize)

Size of numpy array is:  400


In [107]:
list1 = range(0,100)
list1

range(0, 100)

In [108]:
print("Size of list: ",sys.getsizeof(1)*len(list1))

Size of list:  2800


# Fast Computation of NumPy array

In [109]:
size = 10000
list1 = range(size)
list2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [(x,y) for x,y in zip(list1,list2)]

print("Time for list = ", (time.time()-start)*1000)

start = time.time()
result = a1+a2
print("Time for numpy array = ", (time.time()-start)*1000)


Time for list =  7.995843887329102
Time for numpy array =  2.99072265625


# numpy.moveaxis 

#### Syntax 
numpy.moveaxis(a, source, destination)

Move axes of an array to new positions. Other axes remain in their original order.


In [110]:
import numpy as np
x=np.array([[[1,2,5,6,77],[3,4,1,4,5],[4,6,3,7,8],[9,7,1,2,3]],
            [[5,6,12,34,55],[23,4,55,67,88],[7,8,12,34,43],
             [23,44,567,12,234]]])
print(x)
print(x.shape)

[[[  1   2   5   6  77]
  [  3   4   1   4   5]
  [  4   6   3   7   8]
  [  9   7   1   2   3]]

 [[  5   6  12  34  55]
  [ 23   4  55  67  88]
  [  7   8  12  34  43]
  [ 23  44 567  12 234]]]
(2, 4, 5)


In [111]:
sum1 = np.max(x,axis = 2)
sum1

array([[ 77,   5,   8,   9],
       [ 55,  88,  43, 567]])

In [112]:
sum3 = np.max(x,axis=0)
sum3

array([[  5,   6,  12,  34,  77],
       [ 23,   4,  55,  67,  88],
       [  7,   8,  12,  34,  43],
       [ 23,  44, 567,  12, 234]])

In [113]:
sum2 = np.max(x,axis=1)
sum2

array([[  9,   7,   5,   7,  77],
       [ 23,  44, 567,  67, 234]])

In [114]:
a = np.moveaxis(x,0,-1)
a.shape

(4, 5, 2)

In [115]:
print(x)
print(a)

[[[  1   2   5   6  77]
  [  3   4   1   4   5]
  [  4   6   3   7   8]
  [  9   7   1   2   3]]

 [[  5   6  12  34  55]
  [ 23   4  55  67  88]
  [  7   8  12  34  43]
  [ 23  44 567  12 234]]]
[[[  1   5]
  [  2   6]
  [  5  12]
  [  6  34]
  [ 77  55]]

 [[  3  23]
  [  4   4]
  [  1  55]
  [  4  67]
  [  5  88]]

 [[  4   7]
  [  6   8]
  [  3  12]
  [  7  34]
  [  8  43]]

 [[  9  23]
  [  7  44]
  [  1 567]
  [  2  12]
  [  3 234]]]


In [116]:
b = np.moveaxis(x,1,2)

In [117]:
b.shape

(2, 5, 4)

In [118]:
print(b)

[[[  1   3   4   9]
  [  2   4   6   7]
  [  5   1   3   1]
  [  6   4   7   2]
  [ 77   5   8   3]]

 [[  5  23   7  23]
  [  6   4   8  44]
  [ 12  55  12 567]
  [ 34  67  34  12]
  [ 55  88  43 234]]]


# Flatten nd array to 1D array

In [119]:
x=np.array([[[1,2,5,6,7],[3,4,1,4,5],[4,6,3,7,8],[9,7,1,2,3]],
            [[5,6,12,34,55],[23,4,55,67,88],[7,8,12,34,43],
             [23,44,567,12,234]]])
oneD=np.ravel(x)
oneD

array([  1,   2,   5,   6,   7,   3,   4,   1,   4,   5,   4,   6,   3,
         7,   8,   9,   7,   1,   2,   3,   5,   6,  12,  34,  55,  23,
         4,  55,  67,  88,   7,   8,  12,  34,  43,  23,  44, 567,  12,
       234])

In [120]:
oneD.shape

(40,)

In [121]:
t = x.reshape(40,)
print(t.shape)
print(t)

(40,)
[  1   2   5   6   7   3   4   1   4   5   4   6   3   7   8   9   7   1
   2   3   5   6  12  34  55  23   4  55  67  88   7   8  12  34  43  23
  44 567  12 234]


# Thanks For watching 
There are lot of things you can learn from me. So follow me.